#194 Program Management Follow-up
HaughtCodeworks/cfp-app pull request #131
Opened 2016-09-27 15:58 UTC by gitcow

- Show finalized proposals on selection index.

- Confirmation notes viewable from selection index & show pages.

- Promote & Decline buttons removed from program proposals show page.

- Removed ::text|confirmation_link:: in favor of markdown's [text](::confirmation_link::) style.

- Language tweaks on speaker confirmation flow.

- Block non-program-team staff from the program pages. Refactored speakers, proposals,
  and program_sessions controllers to inherit from program controller.

- Cleaned up role-checking controller code a bit.

2016-09-27 17:26 UTC, mghaught requested changes
Looks good.  A minor tweak or two via comments.

2016-09-27 17:26 UTC, mghaught commented on app/controllers/application_controller.rb
> +    elsif current_user.staff_for?(current_event)
This should use the user object passed in

2016-09-27 17:26 UTC, mghaught commented on app/controllers/staff/teammates_controller.rb
> +    if @event.contact_email.empty?
Curious about the use of @event when you've got current_event referenced in the rest of the controller.

2016-09-27 17:44 UTC, gitcow commented on app/controllers/application_controller.rb
> +    elsif current_user.staff_for?(current_event)
Ah, thanks

2016-09-29 17:07 UTC, gitcow commented on app/controllers/staff/teammates_controller.rb
> +    if @event.contact_email.empty?
Oh, yep. Looks like I missed that when I copied it over.

2016-09-29 19:40 UTC, mghaught approved these changes

2016-09-29 19:46 UTC, merged