Improve notifications settings flow for team members (#259)
HaughtCodeworks/cfp-app pull request #193
Opened 2018-01-08 19:03 UTC by jonsgreen

- Add email preferences to teammates for tracking notification prefs
- manage preferences for all events from profile form

Improve notifications settings flow for team members (#259)

2018-01-09 19:28 UTC, jeneve requested changes

2018-01-09 19:28 UTC, jeneve commented on db/seeds.rb
> +    binding.pry
oops, remove this

2018-01-10 17:47 UTC, mghaught approved these changes

2018-01-20 00:04 UTC, mghaught approved these changes

2018-01-20 00:06 UTC, merged